name: 'Combine dependabot PRs'

# Controls when the action will run - in this case triggered manually
on:
  workflow_dispatch:
    inputs:
      branchPrefix:
        description: 'Branch prefix to find combinable PRs based on'
        required: true
        default: 'dependabot'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "combine-prs"
  combine-prs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: bobvanderlinden/combine-pull-requests@v2
      name: Create Combined Pull Request
      with:
          # The label to look for pull requests
          label: dependencies 
          # The author name of the merge commit
          author-name: dependabot
          # The author email of the merge commit
          author-email: # optional, default is nobody@nobody
          repo-token: ${{secrets.USER_TOKEN}}
